[project]
name = 'VEX-Py'
version = '23.2.10'

description = 'API Stubs for VEXcode Python & Robot Mesh VEX Python B'
readme = {file = 'README.md', content-type = 'text/markdown', charset = 'UTF-8'}

requires-python = '>= 3.11'

license = {text = 'MIT'}

authors = [
  {name = 'The Vinh LUONG (LƯƠNG Thế Vinh)', email = 'Vinh@STEAMforVietnam.org'}
]
maintainers = [
  {name = 'The Vinh LUONG (LƯƠNG Thế Vinh)', email = 'Vinh@STEAMforVietnam.org'},
  {name = 'STEAM for Vietnam Foundation: Robotics & AI Educational Initative', email = 'Edu.Robotics@STEAMforVietnam.org'}
]

keywords = [
  'Robot Mesh',
  'VEXcode',
  'VEX',
  'Robotics',
]
classifiers = [
  'Development Status :: 4 - Beta',
  'Framework :: Robot Framework',
  'Framework :: Robot Framework :: Library',
  'Framework :: Robot Framework :: Tool',
  'Intended Audience :: Education',
  'Operating System :: MacOS',
  'Operating System :: MacOS :: MacOS X',
  'Operating System :: Microsoft :: Windows',
  'Operating System :: POSIX :: Linux',
  'Programming Language :: Python',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.11',
  'Programming Language :: Python :: 3.12',
  'Topic :: Education',
  'Topic :: Scientific/Engineering',
  'Topic :: Software Development :: Libraries :: Python Modules',
]

dependencies = [
  'Agent-Behavior-Model >= 23.1.25',
]


[project.urls]
Homepage = 'https://GitHub.com/VEX-Robotics-AI/VEX-Py'
Documentation = 'https://GitHub.com/VEX-Robotics-AI/VEX-Py'
GitHub = 'https://GitHub.com/VEX-Robotics-AI/VEX-Py'
Repository = 'https://GitHub.com/VEX-Robotics-AI/VEX-Py'


[project.scripts]


[project.optional-dependencies]
build = [
  'Build >= 0.10.0',
]

doc = [
  # Sphinx & related
  'Sphinx >= 6.1.3',
  'Sphinx-AutoBuild >= 2021.3.14',
  'SphinxContrib-JSMath >= 1.0.1',

  # Markdown
  'CommonMark >= 0.9.1',
  # 'MyST-Parser >= 0.18.1',  # depends on sphinx<6 and >=4
  'ReCommonMark >= 0.7.1',
]

lint = [
  'Bandit >= 1.7.4',
  'Flake8 >= 6.0.0',
  'MyPy >= 1.0.0',
  # 'Prospector >= 1.8.4',
  'PyCodeStyle >= 2.10.0',
  'PyDocStyle >= 6.3.0',
  'PyLama >= 8.4.1',
  'PyLint >= 2.16.1',
]

publish = [
  'Twine >= 4.0.2',
]

test = [
  'Nose >= 1.3.7',
  'Nose2 >= 0.12.0',
  'PyTest >= 7.2.1',
  'PyTest-Cov >= 4.0.0',
  'UnitTest2 >= 1.1.0',
]


[build-system]
requires = [
  'SetUpTools >= 67.2.0',
  'Wheel >= 0.38.4',
]
build-backend = 'setuptools.build_meta'
