[project]
name = 'RobotMesh-VEX-PyB-API-Stubs'
version = '1.0.8'

description = 'Robot Mesh VEX Python B API Stubs'
readme = {file = 'README.md', content-type = 'text/markdown', charset = 'UTF-8'}

requires-python = '>= 3.9'

license = {text = 'MIT'}

authors = [
  {name = 'The Vinh LUONG (LƯƠNG Thế Vinh)', email = 'Vinh@STEAMforVietnam.org'}
]
maintainers = [
  {name = 'The Vinh LUONG (LƯƠNG Thế Vinh)', email = 'Vinh@STEAMforVietnam.org'}
]

keywords = [
  'Robot Mesh',
  'VEX',
  'Robotics',
]
classifiers = [
  'Development Status :: 4 - Beta', 
  'Framework :: Robot Framework',
  'Framework :: Robot Framework :: Library',
  'Framework :: Robot Framework :: Tool',
  'Intended Audience :: Education',
  'Operating System :: MacOS',
  'Operating System :: MacOS :: MacOS X',
  'Operating System :: Microsoft :: Windows',
  'Operating System :: POSIX :: Linux',
  'Programming Language :: Python',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.9',
  'Programming Language :: Python :: 3.10',
  'Topic :: Education',
  'Topic :: Scientific/Engineering',
  'Topic :: Software Development :: Libraries :: Python Modules',
]


[project.urls]
Homepage = 'https://GitHub.com/VEX-Robotics-AI/RobotMesh-VEX-PyB-API-Stubs'
Documentation = 'https://GitHub.com/VEX-Robotics-AI/RobotMesh-VEX-PyB-API-Stubs'
GitHub = 'https://GitHub.com/VEX-Robotics-AI/RobotMesh-VEX-PyB-API-Stubs'
Repository = 'https://GitHub.com/VEX-Robotics-AI/RobotMesh-VEX-PyB-API-Stubs'


[project.scripts]
robotmesh-vex = 'vex._cli:robotmesh_vex_cli'


[project.dependencies]
CLICK = '^8.0.4'
Decorator = '>= 5.1.1'
Wrapt = '>= 1.14.0'

[project.optional-dependencies]
devtest = [
  'Nose2 >= 0.11.0',
  'PyTest >= 7.1.1',
]


[build-system]
requires = [
  'SetUpTools >= 60.10.0',
  'Wheel >= 0.37.1',
]
build-backend = 'setuptools.build_meta'
